// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nxio.Core.Database;

#nullable disable

namespace Nxio.Core.Database.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    partial class BaseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nxio.Core.Database.Models.CoinMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("MessageId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "MessageId")
                        .IsUnique();

                    b.ToTable("CoinMessages");
                });

            modelBuilder.Entity("Nxio.Core.Database.Models.CoinReaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CoinMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CoinMessageId");

                    b.HasIndex("UserId");

                    b.ToTable("CoinReactions");
                });

            modelBuilder.Entity("Nxio.Core.Database.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Coins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("UserDiscordId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Nxio.Core.Database.Models.CoinReaction", b =>
                {
                    b.HasOne("Nxio.Core.Database.Models.CoinMessage", "CoinMessage")
                        .WithMany("Reactions")
                        .HasForeignKey("CoinMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nxio.Core.Database.Models.User", "User")
                        .WithMany("CoinReactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoinMessage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nxio.Core.Database.Models.CoinMessage", b =>
                {
                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("Nxio.Core.Database.Models.User", b =>
                {
                    b.Navigation("CoinReactions");
                });
#pragma warning restore 612, 618
        }
    }
}
