name: "CI"

on:
  pull_request:
    branches: [ 'master' ]
  push:
    branches: [ 'master' ]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

permissions: write-all

jobs:
  format-build-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-24.04', 'windows-2025' ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Setup .NET"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
      - name: "Restore dependencies"
        run: dotnet restore
      - name: "Format"
        run: dotnet format --severity info --verbosity diagnostic --exclude ./Nxio.Core/Database/Migrations/ --verify-no-changes
      - name: "Build"
        run: dotnet build --no-restore --configuration Release --verbosity minimal
      - name: "Test"
        run: dotnet test --no-build --no-restore --configuration Release --verbosity normal


  resharper-scan:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-24.04' ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Setup .NET"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
      - name: 'Annotate'
        uses: JetBrains/ReSharper-InspectCode@v0.8
        with:
          solution: ./Nxio.sln
          swea: true
          build: true

  code-ql:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-24.04' ]
        include:
          - language: csharp
            build-mode: manual
    runs-on: ${{ matrix.os }}
    steps:
    - name: "Checkout repo"
      uses: actions/checkout@v4
    - name: "Setup .NET"
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x
    - name: 'Initialize CodeQL'
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        build-mode: ${{ matrix.build-mode }}
        queries: security-and-quality
    - name: "Restore dependencies"
      run: dotnet restore
    - name: "Build"
      run: dotnet build --no-restore --configuration Release --verbosity minimal
    - name: 'Perform CodeQL Analysis'
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"