name: "CI"

on:
  pull_request:
    branches: [ 'master' ]
  push:
    branches: [ 'master' ]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

concurrency:
  group: '${{ github.head_ref || github.run_id }}-${{ github.workflow }}'
  cancel-in-progress: true

permissions: write-all

jobs:
  backend:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest' ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Setup .NET"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
      - name: "Restore dependencies"
        run: dotnet restore
      - name: "Format"
        run: dotnet format --severity info -v diag --exclude ./Nxio.Core/Database/Migrations/ --verify-no-changes
      - name: "Build"
        run: dotnet build --no-restore --configuration Release --verbosity m
      - name: "Test"
        run: dotnet test --no-build --no-restore --configuration Release --verbosity n